src/main/java/com/springapp/model/domain/Supplier.java
package com.springapp.model.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Set;

@Entity
@Table(name = "Supplier")
public class Supplier implements Serializable {

    private Long supplierId;
    @Column(nullable = false, unique = true)
    private String email;
    @Column(unique = true)
    private int fax;
    private String name, address, city, country, postalcode;
    @Column(unique = true)
    private int phone;
    private Set<Product> product;


    public Supplier() {
        super();
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getFax() {
        return fax;
    }

    public void setFax(int fax) {
        this.fax = fax;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPhone() {
        return phone;
    }

    public void setPhone(int phone) {
        this.phone = phone;
    }

    public String getPostalcode() {
        return postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    @OneToMany(fetch = FetchType.EAGER)
    public Set<Product> getProducts() {
        return product;
    }

    public void setProducts(Set<Product> product) {
        this.product = product;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    @Override
    public String toString() {
        return "Supplier{" +
                "supplierId=" + supplierId +
                ", email='" + email + '\'' +
                ", fax=" + fax +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", city='" + city + '\'' +
                ", country='" + country + '\'' +
                ", postalcode='" + postalcode + '\'' +
                ", phone=" + phone +
                ", product=" + product +
                '}';
    }
}

src/main/java/com/springapp/controller/CategoryController.java
package com.springapp.controller;

import com.springapp.model.domain.Category;
import com.springapp.model.service.CategoryBO;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping("/category")
public class CategoryController {

    @Autowired
    private CategoryBO categoryBO;


    @RequestMapping({"/",""})
    public String manageCategories(ModelMap model) {
        model.addAttribute("category", new Category());
        model.addAttribute("categories", categoryBO.readAll());
        return "category";
    }

    @RequestMapping(value = {"add","/add"}, method = RequestMethod.POST)
    public String createCategory(@ModelAttribute Category category, ModelMap model, BindingResult result) {
        if (result.hasErrors()) {
            model.addAttribute("errors", result.getAllErrors());
        } else {
            categoryBO.create(category);
        }
        return "redirect:/category/";
    }

    @RequestMapping({"/delete/{categoryId}","delete/{categoryId}"})
    public String deleteCategory(@PathVariable("categoryId") long categoryId) {
        Category cat = categoryBO.read(categoryId);
        categoryBO.delete(cat);
        return "redirect:/category/";
    }

    /*

    API

     */

    @RequestMapping({"/api","api"})
    public @ResponseBody String readAllJson() {
        JSONArray jsonArray = new JSONArray();
        for (Category category : categoryBO.readAll()) {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("categoryId", category.getCategoryId());
            jsonObject.put("name", category.getName());
            jsonObject.put("description", category.getDescription());
            jsonArray.put(jsonObject);
        }
        return jsonArray.toString();
    }

    @RequestMapping({"/api/{name}","api/{name}"})
    public @ResponseBody String readJson(@PathVariable("name") String name) {
        Category category = categoryBO.readByName(name);
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("categoryId", category.getCategoryId());
            jsonObject.put("name", category.getName());
            jsonObject.put("description", category.getDescription());
        return jsonObject.toString();
    }


}

src/main/java/com/springapp/controller/CourierController.java
package com.springapp.controller;

import com.springapp.model.service.CourierBO;
import com.springapp.model.domain.Courier;
import org.apache.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping("/courier")
public class CourierController {

    private static Logger logger = Logger.getLogger(CourierController.class);

    @Autowired
    private CourierBO courierBO;

    @RequestMapping("/")
    public String showCouriers(ModelMap model) {
        model.addAttribute("courier", new Courier());
        model.addAttribute("couriers", courierBO.readAll());
        if (logger.isInfoEnabled())
            logger.info("Courier Add/Delete section");
        return "courier";
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    public String addCourier(@ModelAttribute("courier") Courier courier, BindingResult result) {
        courierBO.create(courier);
        if (logger.isInfoEnabled())
            logger.info("Added courier: " + courier);
        return "redirect:/courier/";
    }

    @RequestMapping("/delete/{courierId}")
    public String deleteCourier(@PathVariable("courierId") Long courierId) {
        Courier courier = courierBO.read(courierId);
        courierBO.delete(courier);
        if (logger.isInfoEnabled())
            logger.info("Deleted courier " + courier);
        return "redirect:/courier/";
    }

    /*

    API

     */


    @RequestMapping(value="/api/", method = RequestMethod.GET)
    public @ResponseBody String getJSONAll () {
        JSONArray courierArray = new JSONArray();
        for (Courier courier: courierBO.readAll()) {
            JSONObject courierObject = new JSONObject();
            courierObject.put("courierId", courier.getCourierId());
            courierObject.put("name", courier.getName());
            courierObject.put("phone", courier.getPhone());
            courierArray.put(courierObject);
        }
        if (logger.isInfoEnabled())
            logger.info("Showing all couriers in JSON format");
        return courierArray.toString();
    }

    @RequestMapping(value="/api/{name}", method = RequestMethod.GET)
    public @ResponseBody String getJSON (@PathVariable("name") String name) {
        Courier result = courierBO.findByName(name);
        JSONObject courierObject = new JSONObject();
        courierObject.put("courierId", result.getCourierId());
        courierObject.put("name", result.getName());
        courierObject.put("phone", result.getPhone());
        if (logger.isInfoEnabled())
            logger.info("Showing specific courier in JSON format: " + result);
        return courierObject.toString();
    }

}

src/main/java/com/springapp/controller/CustomerController.java
package com.springapp.controller;

import com.springapp.model.service.CustomerBO;
import com.springapp.model.domain.Customer;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@Controller
@RequestMapping("/customer")
public class CustomerController {

    @Autowired
    private CustomerBO customerBO;

    @RequestMapping("/")
    public String showCustomer(ModelMap model) {
        model.addAttribute("customer", new Customer());
        model.addAttribute("customers", customerBO.readAll());
        return "customer";
    }

    @RequestMapping(value="add", method = RequestMethod.POST)
    public String addCustomer(@ModelAttribute("customer") Customer customer, BindingResult result) {
        customerBO.create(customer);
        return "redirect:/customer/";
    }

    @RequestMapping("delete/{customerId}")
    public String deleteCustomer(@PathVariable("customerId") Long customerId) {
        customerBO.delete(customerBO.read(customerId));
        return "redirect:/customer/";
    }

    /*

    API

     */

    @RequestMapping("api")
    public @ResponseBody String readAllJson() {
        JSONArray jsonArray = new JSONArray();
        for (Customer customer : customerBO.readAll()) {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("customerId", customer.getCustomerId());
            jsonObject.put("firstName", customer.getFirstName());
            jsonObject.put("lastName", customer.getLastName());
            jsonObject.put("phone", customer.getPhone());
            jsonObject.put("email", customer.getEmail());
            jsonObject.put("street", customer.getStreet());
            jsonObject.put("city", customer.getCity());
            jsonObject.put("postalcode", customer.getPostalcode());
            jsonObject.put("country", customer.getCountry());
            jsonArray.put(jsonObject);
        }
        return jsonArray.toString();
    }

    @RequestMapping("api/{email}")
    public @ResponseBody String readByEmailJson(@PathVariable("email") String email) {
        Customer customer = customerBO.readByEmail(email);
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("customerId", customer.getCustomerId());
            jsonObject.put("firstName", customer.getFirstName());
            jsonObject.put("lastName", customer.getLastName());
            jsonObject.put("phone", customer.getPhone());
            jsonObject.put("email", customer.getEmail());
            jsonObject.put("street", customer.getStreet());
            jsonObject.put("city", customer.getCity());
            jsonObject.put("postalcode", customer.getPostalcode());
            jsonObject.put("country", customer.getCountry());
        return jsonObject.toString();
    }

}

src/main/java/com/springapp/controller/OrderController.java
package com.springapp.controller;

import com.springapp.model.domain.Orders;
import com.springapp.model.service.CourierBO;
import com.springapp.model.service.CustomerBO;
import com.springapp.model.service.OrderBO;
import com.springapp.model.service.PaymentBO;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping("/order")
public class OrderController {

    @Autowired
    private OrderBO orderBO;

    @Autowired
    private CourierBO courierBO;

    @Autowired
    private CustomerBO customerBO;

    @Autowired
    private PaymentBO paymentBO;


    @RequestMapping("/")
    public String showOrders(ModelMap model) {
        model.addAttribute("order", new Orders());
        model.addAttribute("orders", orderBO.readAll());
        model.addAttribute("couriers", courierBO.readAll());
        model.addAttribute("customers", customerBO.readAll());
        model.addAttribute("payments", paymentBO.readAll());
        return "order";
    }

    @RequestMapping(value = "add", method = RequestMethod.POST)
    public String createOrder(@ModelAttribute Orders order, @RequestParam long courierId, @RequestParam long customerId, @RequestParam long paymentId) {
        order.setCourier(courierBO.read(courierId));
        order.setCustomer(customerBO.read(customerId));
        order.setPayment(paymentBO.read(paymentId));
        orderBO.create(order);
        return "redirect:/order/";
    }

    @RequestMapping("delete/{orderId}")
    public String deleteOrder(@PathVariable("orderId") long orderId) {
        orderBO.delete(orderBO.read(orderId));
        return "redirect:/order/";
    }

    /*

    REST/API ...

     */

    @RequestMapping("api")
    public @ResponseBody String readAllJson() {
        JSONArray orderArray = new JSONArray();
        for (Orders order : orderBO.readAll()) {
            JSONObject orderObject = new JSONObject();
            orderObject.put("orderId", order.getOrderId());
            orderObject.put("status", order.getStatus());
            orderObject.put("tax",order.getTax());
            orderObject.put("paid", order.isPaid());
            orderObject.put("date", order.getTimestamp());
            orderArray.put(orderObject);
        }
        return orderArray.toString();
    }

    @RequestMapping("api/{orderId}.json")
    public @ResponseBody String readJson(@PathVariable("orderId") long orderId) {
        Orders order = orderBO.read(orderId);
        JSONObject orderObject = new JSONObject();
        orderObject.put("orderId", order.getOrderId());
        orderObject.put("status", order.getStatus());
        orderObject.put("tax",order.getTax());
        orderObject.put("paid", order.isPaid());
        orderObject.put("date", order.getTimestamp());
        return orderObject.toString();
    }



}

src/main/java/com/springapp/controller/OrderDetailsController.java
package com.springapp.controller;

import com.springapp.model.domain.OrderDetails;
import com.springapp.model.service.OrderBO;
import com.springapp.model.service.OrderDetailsBO;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/orderdetails")
public class OrderDetailsController {

    @Autowired
    private OrderDetailsBO orderDetailsBO;

    @Autowired
    private OrderBO orderBO;

    @RequestMapping("/")
    public String showOrderDetails(ModelMap model) {
        model.addAttribute("orderdetail", new OrderDetails());
        model.addAttribute("orders", orderBO.readAll());
        model.addAttribute("orderdetails", orderDetailsBO.readAll());
        return "orderdetails";
    }

    @RequestMapping( value = "/add", method = RequestMethod.POST)
    public String createOrderDetail(@ModelAttribute OrderDetails orderDetails, @RequestParam long orderId) {
        orderDetails.setOrder(orderBO.read(orderId));
        orderDetailsBO.create(orderDetails);
        return "redirect:/orderdetails/";
    }

    @RequestMapping("/delete/{orderDetailsId}")
    public String deleteOrderDetail(@PathVariable("orderDetailsId") long orderDetailsId) {
        orderDetailsBO.delete(orderDetailsBO.read(orderDetailsId));
        return "redirect:/orderdetails";
    }

    /*

    API /REST

     */

    @RequestMapping("/api")
    public @ResponseBody String readAllJson() {
        JSONArray jsonArray = new JSONArray();
        for (OrderDetails orderDetails : orderDetailsBO.readAll()) {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("orderDetailsId",orderDetails.getOrderDetailsId());
            jsonObject.put("amount",orderDetails.getAmount());
            jsonObject.put("price", orderDetails.getPrice());
            jsonObject.put("total", orderDetails.getTotal());
            jsonArray.put(jsonObject);
        }
        return jsonArray.toString();
    }


    @RequestMapping("/api/{orderDetailsId}")
    public @ResponseBody String readJson(@PathVariable("orderDetailsId") long orderDetailsId) {
        OrderDetails orderDetails = orderDetailsBO.read(orderDetailsId);
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("orderDetailsId",orderDetails.getOrderDetailsId());
            jsonObject.put("amount",orderDetails.getAmount());
            jsonObject.put("price", orderDetails.getPrice());
            jsonObject.put("total", orderDetails.getTotal());
        return jsonObject.toString();
    }

}

src/main/webapp/WEB-INF/pages/category.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Category</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span8 offset2">
            <a href="api">JSON (all)</a>
            <h1>Add Category</h1>
            <form:form method="post" action="add" commandName="category" class="form-horizontal">
                <div class="control-group">
                    <form:label cssClass="control-label" path="name">Name:</form:label>
                    <div class="controls">
                        <form:input path="name"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="description">Description:</form:label>
                    <div class="controls">
                        <form:textarea path="description"/>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Add Category" class="btn">
                    </div>
                </div>
            </form:form>

            <c:if test="${!empty categories}">
                <h3>Categories</h3>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Products</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${categories}" var="category">
                        <tr>
                            <td>${category.name}</td>
                            <td>
                                <ul>
                                <c:forEach items="${category.products}" var="product">
                                    <li>${product.name}</li>
                                </c:forEach>
                                </ul>
                            </td>
                            <td>
                                <a href="api/${category.name}.json">JSON</a>
                                <form action="delete/${category.categoryId}" method="post"><input type="submit" class="btn btn-danger btn-mini" value="Delete"/></form>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </c:if>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/pages/courier.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Courier</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span8 offset2">
            <a href="api/">JSON (all)</a>
            <h1>Add Courier</h1>
            <form:form method="post" action="add" commandName="courier" class="form-horizontal">
                <div class="control-group">
                    <form:label cssClass="control-label" path="name">Name:</form:label>
                    <div class="controls">
                        <form:input path="name"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="phone">Phone:</form:label>
                    <div class="controls">
                        <form:input path="phone"/>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Add Courier" class="btn">
                    </div>
                </div>
            </form:form>

            <c:if test="${!empty couriers}">
                <h3>Couriers</h3>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${couriers}" var="courier">
                        <tr>
                            <td>${courier.name}</td>
                            <td>${courier.phone}</td>
                            <td>
                                <a href="api/${courier.name}.json">JSON</a>
                                <form action="delete/${courier.courierId}" method="post"><input type="submit" class="btn btn-danger btn-mini" value="Delete"/></form>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </c:if>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/pages/customer.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Customer</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span8 offset2">
            <a href="api">JSON (all)</a>
            <h1>Add Customer</h1>
            <form:form method="post" action="add" commandName="customer" class="form-horizontal">
                <div class="control-group">
                    <form:label cssClass="control-label" path="email">Email:</form:label>
                    <div class="controls">
                        <form:input path="email"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="firstName">First Name:</form:label>
                    <div class="controls">
                        <form:input path="firstName"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="lastName">Last Name:</form:label>
                    <div class="controls">
                        <form:input path="lastName"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="street">Street:</form:label>
                    <div class="controls">
                        <form:input path="street"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="postalcode">Postal code:</form:label>
                    <div class="controls">
                        <form:input path="postalcode"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="country">Country:</form:label>
                    <div class="controls">
                        <form:input path="country"/>
                    </div>
                </div>
                <div class="control-group">
                    <form:label cssClass="control-label" path="phone">Phone:</form:label>
                    <div class="controls">
                        <form:input path="phone"/>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Add Customer" class="btn">
                    </div>
                </div>
            </form:form>

            <c:if test="${!empty customers}">
                <h3>Categories</h3>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${customers}" var="customer">
                        <tr>
                            <td>${customer.email}</td>
                            <td>${customer.firstName}</td>
                            <td>${customer.lastName}</td>
                            <td>
                                <a href="api/${customer.email}.json">JSON</a>
                                <form action="delete/${customer.customerId}" method="post"><input type="submit" class="btn btn-danger btn-mini" value="Delete"/></form>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </c:if>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/pages/hello.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Ordering system</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span8 offset2">
            <div class="page-header">
                <h1>Ordering system <small>by Dennis Tusk</small></h1>
            </div>
        </div>
        <h3>Links</h3>
        <ul class="list-group">
            <li class="list-group-item"><a href="courier/">Couriers</a></li> <!-- Zrobione -->
            <li class="list-group-item"><a href="product/">Products</a></li>  <!-- Zrobione -->
            <li class="list-group-item"><a href="customer/">Customers</a></li>  <!-- Zrobione -->
            <li class="list-group-item"><a href="supplier/">Suppliers</a></li>  <!-- Zrobione -->
            <li class="list-group-item"><a href="category/">Categories</a></li>  <!-- Zrobione -->
            <li class="list-group-item"><a href="payment/">Payments</a></li>   <!-- Zrobione -->
            <li class="list-group-item"><a href="order/">Orders</a></li>
            <li class="list-group-item"><a href="orderdetails/">Order Details</a></li>
        </ul>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/pages/payment.jsp
<%--
  Date: 25.11.13
  Time: 17:15
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Payment</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

<div class="container">
    <div class="row">
        <a href="api/">json (all)</a>
        <div class="span8 offset2">
            <h1>Add Payment</h1>
            <form:form method="post" action="add" commandName="payment" class="form-horizontal">
                <div class="control-group">
                    <form:label cssClass="control-label" path="type">Type:</form:label>
                    <div class="controls">
                        <form:input path="type"/>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" value="Add Payment" class="btn">
                    </div>
                </div>
            </form:form>

            <c:if test="${!empty payments}">
                <h3>Payments</h3>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${payments}" var="payment">
                        <tr>
                            <td>${payment.type}</td>
                            <td>
                                <form action="delete/${payment.paymentId}" method="post"><input type="submit" class="btn btn-danger btn-mini" value="Delete"/></form>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </c:if>
        </div>
    </div>
</div>

</body>
</html>